# Generated by Django 5.0.4 on 2024-08-26 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='開始時間')),
                ('end', models.DateTimeField(verbose_name='終了時間')),
                ('name', models.CharField(max_length=255, verbose_name='予約者名')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='メモ')),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='staff',
            name='unique_staff',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='store',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='user',
        ),
        migrations.AddField(
            model_name='staff',
            name='Division',
            field=models.CharField(default='デフォルト値', max_length=50, verbose_name='支社'),
        ),
        migrations.AddField(
            model_name='staff',
            name='ISBN',
            field=models.CharField(default='デフォルト値', max_length=50, verbose_name='ISBN'),
        ),
        migrations.AddField(
            model_name='staff',
            name='author',
            field=models.CharField(default='デフォルト値', max_length=50, verbose_name='著者'),
        ),
        migrations.AddField(
            model_name='staff',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='表紙画像'),
        ),
        migrations.AddField(
            model_name='staff',
            name='publisher',
            field=models.CharField(default='デフォルト値', max_length=50, verbose_name='出版社'),
        ),
        migrations.AddField(
            model_name='staff',
            name='section',
            field=models.CharField(default='デフォルト値', max_length=50, verbose_name='セクション'),
        ),
        migrations.AddField(
            model_name='staff',
            name='shelf',
            field=models.CharField(default='デフォルト値', max_length=50, verbose_name='棚'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.staff', verbose_name='占いスタッフ'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(default='デフォルト値', max_length=50, verbose_name='表示名'),
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.staff', verbose_name='占いスタッフ'),
        ),
        migrations.AddConstraint(
            model_name='bookinfo',
            constraint=models.UniqueConstraint(fields=('staff', 'start', 'end'), name='unique_schedule'),
        ),
    ]
