# Generated by Django 5.0.4 on 2024-08-26 04:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_bookinfo_remove_staff_unique_staff_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bookinfo',
            name='unique_schedule',
        ),
        migrations.RemoveField(
            model_name='bookinfo',
            name='end',
        ),
        migrations.RemoveField(
            model_name='bookinfo',
            name='memo',
        ),
        migrations.RemoveField(
            model_name='bookinfo',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='bookinfo',
            name='start',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='Division',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='ISBN',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='author',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='section',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='shelf',
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='Division',
            field=models.CharField(default='デフォルト値', max_length=50, verbose_name='支社'),
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='ISBN',
            field=models.CharField(default='デフォルト値', max_length=50, verbose_name='ISBN'),
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='author',
            field=models.CharField(default='デフォルト値', max_length=50, verbose_name='著者'),
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='表紙画像'),
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='publisher',
            field=models.CharField(default='デフォルト値', max_length=50, verbose_name='出版社'),
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='section',
            field=models.CharField(default='デフォルト値', max_length=50, verbose_name='セクション'),
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='shelf',
            field=models.CharField(default='デフォルト値', max_length=50, verbose_name='棚'),
        ),
        migrations.AddField(
            model_name='staff',
            name='end',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='終了時間'),
        ),
        migrations.AddField(
            model_name='staff',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='メモ'),
        ),
        migrations.AddField(
            model_name='staff',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_staff', to='booking.staff'),
        ),
        migrations.AddField(
            model_name='staff',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='開始時間'),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='name',
            field=models.CharField(default='デフォルト値', max_length=50, verbose_name='表示名'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(max_length=255, verbose_name='予約者名'),
        ),
        migrations.AddConstraint(
            model_name='staff',
            constraint=models.UniqueConstraint(fields=('staff', 'start', 'end'), name='unique_schedule'),
        ),
    ]
